@startuml

title __LOGGING's Class Diagram__\n

  namespace  {
    class FileErrorManager {
        - emailStore : File
        {static} - manager : LogManager
        - next : ErrorManager
        + FileErrorManager()
        + FileErrorManager()
        + error()
        - close()
        - delete()
        - getEmailStore()
        - init()
        - isRawEmail()
        - prefixName()
        - storeEmail()
        - suffixName()
    }
  }
  

  namespace  {
    class MailHandlerDemo {
        {static} - CLASS_NAME : String
        {static} - LOGGER : Logger
        {static} - pushNormalHandler : Handler
        {static} - pushOnlyHandler : Handler
        {static} + main()
        {static} - applyFallbackSettings()
        {static} - checkConfig()
        {static} - closeHandlers()
        {static} - fallbackSettings()
        {static} - getConfigLocation()
        {static} - getTempDir()
        {static} - init()
        {static} - initBodyOnly()
        {static} - initCustomAttachments()
        {static} - initLowCapacity()
        {static} - initPushNormal()
        {static} - initPushOnly()
        {static} - initSimpleAttachment()
        {static} - initWithPushFilter()
        {static} - initWithPushLevel()
    }
  }
  

  namespace  {
    class MailHandlerDemo.LevelAndSeqComparator {
        - reverse : boolean
        {static} - serialVersionUID : long
        + compare()
        ~ LevelAndSeqComparator()
        ~ LevelAndSeqComparator()
        - compareSeq()
    }
  }
  

  namespace  {
    class MailHandlerDemo.MessageErrorsFilter {
        - complement : boolean
        + isLoggable()
        ~ MessageErrorsFilter()
    }
  }
  

  namespace  {
    class SummaryFormatter {
        - count : long
        - newest : long
        - oldest : long
        + SummaryFormatter()
        + format()
        + getTail()
        + toString()
        - formatNow()
        {static} - newLine()
        - reset()
        - track()
    }
  }
  

  namespace  {
    class SummaryNameFormatter {
        - count : long
        - errors : long
        - pattern : String
        + SummaryNameFormatter()
        + SummaryNameFormatter()
        + format()
        + getTail()
        + toString()
        - extFrom()
        - toString()
    }
  }
  

  FileErrorManager -up-|> java.util.logging.ErrorManager
  MailHandlerDemo +-down- MailHandlerDemo.LevelAndSeqComparator
  MailHandlerDemo +-down- MailHandlerDemo.MessageErrorsFilter
  MailHandlerDemo.LevelAndSeqComparator .up.|> java.io.Serializable
  MailHandlerDemo.LevelAndSeqComparator .up.|> java.util.Comparator
  MailHandlerDemo.MessageErrorsFilter .up.|> java.util.logging.Filter
  SummaryFormatter -up-|> java.util.logging.Formatter
  SummaryNameFormatter -up-|> java.util.logging.Formatter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
